import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

const ACCENT_BRIGHT = 0x9fd1f2;
const LINE = 0x2a2a2c;

export class HeroScene {
  /**
     * @param {HTMLElement} container - element that will host the canvas
        */
          constructor(container) {
              this.container = container;
                  this.pointer = { x: 0, y: 0 };
                      this.targetRotation = { x: 0, y: 0 };
                          this.clock = new THREE.Clock();
                              this.destroyed = false;

                                  this._initScene();
                                      this._loadAssemblyModel();
                                          this._bindEvents();
                                              this._resize();
                                                  this._tick();
                                                    }

                                                      _initScene() {
                                                          this.scene = new THREE.Scene();

                                                              this.camera = new THREE.PerspectiveCamera(45, 1, 0.1, 100);
                                                                  this.camera.position.set(0, 0, 8);

                                                                      this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
                                                                          this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
                                                                              this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
                                                                                  this.renderer.toneMappingExposure = 1.2;
                                                                                      this.container.appendChild(this.renderer.domElement);

                                                                                          // Dynamic studio lighting to preserve full mesh colors (Yellow/Green/Blue)
                                                                                              const ambientLight = new THREE.AmbientLight(0xffffff, 1.2);
                                                                                                  this.scene.add(ambientLight);

                                                                                                      const dirLight1 = new THREE.DirectionalLight(0xffffff, 2.5);
                                                                                                          dirLight1.position.set(5, 10, 7);
                                                                                                              this.scene.add(dirLight1);

                                                                                                                  const dirLight2 = new THREE.DirectionalLight(ACCENT_BRIGHT, 1.5);
                                                                                                                      dirLight2.position.set(-5, -5, -5);
                                                                                                                          this.scene.add(dirLight2);

                                                                                                                              // Starfield points for background depth
                                                                                                                                  const starGeo = new THREE.BufferGeometry();
                                                                                                                                      const starCount = 180;
                                                                                                                                          const positions = new Float32Array(starCount * 3);
                                                                                                                                              for (let i = 0; i < starCount * 3; i++) {
                                                                                                                                                    positions[i] = (Math.random() - 0.5) * 30;
                                                                                                                                                        }
                                                                                                                                                            starGeo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
                                                                                                                                                                const starMat = new THREE.PointsMaterial({ color: LINE, size: 0.035 });
                                                                                                                                                                    this.stars = new THREE.Points(starGeo, starMat);
                                                                                                                                                                        this.scene.add(this.stars);

                                                                                                                                                                            this.rig = new THREE.Group();
                                                                                                                                                                                this.scene.add(this.rig);
                                                                                                                                                                                  }

                                                                                                                                                                                    async _loadAssemblyModel() {
                                                                                                                                                                                        const loader = new GLTFLoader();

                                                                                                                                                                                            try {
                                                                                                                                                                                                  const { scene: model } = await loader.loadAsync('/models/my-assembly.glb');

                                                                                                                                                                                                        // Preserve original colors and materials from STEP/GLTF
                                                                                                                                                                                                              model.traverse((child) => {
                                                                                                                                                                                                                      if (child.isMesh && child.material) {
                                                                                                                                                                                                                                child.material.side = THREE.DoubleSide;
                                                                                                                                                                                                                                          child.material.needsUpdate = true;
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                              // Auto-center & Scale
                                                                                                                                                                                                                                                                    const box = new THREE.Box3().setFromObject(model);
                                                                                                                                                                                                                                                                          const size = new THREE.Vector3();
                                                                                                                                                                                                                                                                                box.getSize(size);
                                                                                                                                                                                                                                                                                      const maxDim = Math.max(size.x, size.y, size.z) || 1;
                                                                                                                                                                                                                                                                                            const scale = 4.2 / maxDim;
                                                                                                                                                                                                                                                                                                  model.scale.setScalar(scale);

                                                                                                                                                                                                                                                                                                        const center = new THREE.Vector3();
                                                                                                                                                                                                                                                                                                              box.getCenter(center);
                                                                                                                                                                                                                                                                                                                    model.position.sub(center.multiplyScalar(scale));

                                                                                                                                                                                                                                                                                                                          this.rig.add(model);
                                                                                                                                                                                                                                                                                                                                this.part = model;
                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                          console.warn('[Apex Meca] Could not load the assembly model.', error);
                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                  _bindEvents() {
                                                                                                                                                                                                                                                                                                                                                      this._onResize = () => this._resize();
                                                                                                                                                                                                                                                                                                                                                          window.addEventListener('resize', this._onResize);
                                                                                                                                                                                                                                                                                                                                                              this._resizeObserver = new ResizeObserver(this._onResize);
                                                                                                                                                                                                                                                                                                                                                                  this._resizeObserver.observe(this.container);

                                                                                                                                                                                                                                                                                                                                                                      this._onPointerMove = (e) => {
                                                                                                                                                                                                                                                                                                                                                                            const nx = (e.clientX / window.innerWidth) * 2 - 1;
                                                                                                                                                                                                                                                                                                                                                                                  const ny = (e.clientY / window.innerHeight) * 2 - 1;
                                                                                                                                                                                                                                                                                                                                                                                        this.targetRotation.y = nx * 0.5;
                                                                                                                                                                                                                                                                                                                                                                                              this.targetRotation.x = ny * 0.3;
                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                      window.addEventListener('pointermove', this._onPointerMove);
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                          _resize() {
                                                                                                                                                                                                                                                                                                                                                                                                              const { clientWidth: w, clientHeight: h } = this.container;
                                                                                                                                                                                                                                                                                                                                                                                                                  if (!w || !h) return;
                                                                                                                                                                                                                                                                                                                                                                                                                      this.camera.aspect = w / h;
                                                                                                                                                                                                                                                                                                                                                                                                                          this.camera.updateProjectionMatrix();
                                                                                                                                                                                                                                                                                                                                                                                                                              this.renderer.setSize(w, h);
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                  _tick() {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (this.destroyed) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                          const dt = this.clock.getDelta();

                                                                                                                                                                                                                                                                                                                                                                                                                                              if (this.rig) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    this.rig.rotation.y += dt * 0.35; // Idle rotation
                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.rig.rotation.x += (this.targetRotation.x - this.rig.rotation.x) * 0.05;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.rig.rotation.z += (this.targetRotation.y * 0.2 - this.rig.rotation.z) * 0.05;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (this.stars) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.stars.rotation.y += dt * 0.01;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.renderer.render(this.scene, this.camera);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this._raf = requestAnimationFrame(() => this._tick());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              destroy() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.destroyed = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (this._raf) cancelAnimationFrame(this._raf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.removeEventListener('resize', this._onResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this._resizeObserver?.disconnect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.removeEventListener('pointermove', this._onPointerMove);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.renderer.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (this.container && this.renderer.domElement) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                this.container.removeChild(this.renderer.domElement);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }