backend:
  name: git-gateway
  branch: main

media_folder: public/assets/images/blog
public_folder: /assets/images/blog

collections:
  - name: posts
    label: Blog Posts
    label_singular: Blog Post
    folder: src/content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        format: YYYY-MM-DD
        date_format: YYYY-MM-DD
        time_format: false
      - label: Description
        name: description
        widget: text
      - label: Cover Image
        name: coverImage
        widget: image
        required: false
      - label: Tags
        name: tags
        widget: list
        field:
          label: Tag
          name: tag
          widget: string
      - label: Body
        name: body
        widget: markdown
